spring.application.name=StarsFighters

# Server configuration
spring.datasource.url=jdbc:mysql://localhost:3306/stars_fighters?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=Miguel
spring.datasource.password=miguel
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Configuración de OAuth2
spring.security.oauth2.client.registration.google.client-id=303489536851-pus0fqhpjsm9ojuiitj5nubvrtttbpcg.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

#secret JWT
jwt.secret=QzNCNEQ1RTYxMjM0NTY3ODkwQUJDREVGMTIzNDU2Nzg5MEFCQ0RFRjEyMzQ1Njc4OTA=
jwt.expiration=604800000

# Límite de tamaño para subir imágenes en la tienda
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB